food/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='food' # namespaceing the urls

#we are in the /food/urls.py file
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
   # path('<int:item_id>', views.detail, name='detail'),
    path('<int:pk>', views.DetailBasedView.as_view(), name='detail'),
    path('item/', views.item, name='items'),
    path('add', views.CreateItem.as_view(), name='create-item'),
    path('update/<int:item_id>/', views.update_item, name='update-item'),
    path('delete/<int:item_id>/', views.delete_item, name='delete-item'),

    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
    ] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="ff")
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)

    
    def __str__(self):
        return f'{self.user.username} Profile'

food/forms.py
from django import forms
from .models import Item

# Create your models here.
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__" #['item_name', 'item_desc', 'item_price', 'item_image']""

    

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView



class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'items' # this is the name of the object that is passed to the template so it's used for variables
    




#replaced by above
# def index(request):
#     item_list = Item.objects.all()
#     template = loader.get_template('food/index.html')
#     context ={
#         'items': item_list,
#     }

    
#     return render(request, 'food/index.html', context)


# Create your views here.
# def index(request):
#     return HttpResponse("Hello, world. You're at the food index.")

def item(request):
    return HttpResponse("<h1> This is an item view</h1>")


class DetailBasedView(DetailView):
    model = Item
    template_name = 'food/detail.html'
    context_object_name = 'item'
    


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image'] # only the fields in the form
    template_name = 'food/item-form.html'
    #this will get the current user and assign it to the user_name field
    #this is the user that is currently logged in
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    



# def create_item(request):

#     form = ItemForm(request.POST or None)
#     print(f'form is {form}')
#     if form.is_valid():
#         print(f'the form is valid')
#         form.save()
#         return redirect('food:index')
#     print(form.errors)
#     print("form is not valid")
#     #this is used for the default view. the get request. Passes for the form object to the template
#     #context is the dictionary that is passed to the template
#     return render(request, 'food/item-form.html', {'form': form})
    

def update_item(request, item_id):
    print(f"item_id is {item_id}")

    item = Item.objects.get(id=item_id)
    print(f"item is {item}")
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form, 'item': item})


def delete_item (request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/confirm-delete.html', {'item': item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request):
    if request.method == 'POST':
        print("I'm here")
        form = RegisterForm(request.POST) #must use request.POST to get the data from the post request
        
        if form.is_valid():
            form.save()
            print("Its valid")
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'food/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
    <title>Food Index</title>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand" >Food App</a>

    <div class="navbar">
        <a  href="{% url 'food:create-item' %}">Add Item</a>
        <a  href="#">Delete Item</a>
        <a  href="#">View Item</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" >Logout</a>
            <a href="{% url 'profile' %}" >Profile</a>
            {% else %}
            <a href="{% url 'login' %}" >Login</a>
        {% endif%}
    </div>
</nav>
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
    {% endfor %}

{%  endif %}
{% block body %}
{% endblock %}



</body>
</html>

food/templates/food/confirm-delete.html
{% extends 'food/base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <h1>Are you sure you want to delete this item?{{item.item_name}}</h1>
    {{form}}
    <button type="submit" class="btn">confirm</button>
</form>


{% endblock%}

food/templates/food/detail.html
{% extends 'food/base.html'%}
{% comment %} #when using a class based view. You need to pass in an object
that's only if you don't pass in a context_object_name in the view
{% endcomment %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {% comment %} <img src="{{item.item_image}}" alt="item image" class="card" height="300px"/> {% endcomment %}
            </div>
            <div class="col-md-6">
                <h1>{{item.item_name}}</h1>
                <h2>{{item.item_desc}}</h2>
                <h3>${{item.item_price}}</h3>
                <a href="{% url 'food:delete-item' item.id %}" class="btn btn-primary">Delete</a>
                
            </div>
    
    
    </div>


{% endblock%}

food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Food Index</title>
</head>
<body>

{% block body %}

    
    {% for item in items %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                {% comment %} <img class="card" height="150px" src="{{item.item_image}}" alt="item image"/> {% endcomment %}
            
            </div>
            <div class="col-md-4">
                <h1>My Items</h1>
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h5>${{item.item_price}}</h5>
            <h5>Created By {{item.user_name}}</h5>
            </div>
            <div class="col-md-1">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success btn-primary">Details</a>
            </div>
            <div class="col-md-1">
                <a href="{% url 'food:update-item' item.id %}" class="btn btn-success btn-primary">Edit</a>
            </div>
            <div class="col-md-1">
                <a href="{% url 'food:delete-item' item.id %}" class="btn btn-success btn-primary">Delete</a>
            </div>
        </div>
        

        
    {% endfor %}
{% endblock %}




</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>  
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-info" type="submit">add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>  
                    <div class="card-body">
                        <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                {{field}}
                            </div>
                        {%endfor%}
                        <button class="btn-info" type="submit">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <h1>You have been logged out</h1>
    
    
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="profile image"  height="100px" with="100px"/>
{% endblock %}

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>  
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                <br>
                                {{field}}
                            </div>
                        {%endfor%}
                        <button class="btn-info" type="submit">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}